### ISSUE TITLE
Cant display image,and file app.scss

### ISSUE THREAD

**Issue by sethinh** [davidtrushkov/store#1]
Dear Guy
When i try your source i have 2 issues:
1. I cant load file sass/app.sass
2. I cant display image although i fixed right path
it look like:http://qt.localhost/src/public/ProductPhotos/photos/th-c1069fa19d498e9ebf7a9c0b0f8a7937ac411154.jpg 404 (Not Found)
Thank you so much.

**Comment by davidtrushkov** [comment]
The only reason why I think you cant compile sass is you have to install "gulp" and "npm". Found [https://laravel.com/docs/5.2/elixir](here).  If that doesn't work, just create a css file and copy all the code from sass file to your new file, and comment out the sass file in your header, and add the new css in your header.

The file image path has to look something like this when you inspect the source code in you web browser.
`/store/src/public/ProductPhotos/photos/th-50d59eef10574aeb78a8681541ef7e6bf2a3edd5.jpg`

Although it probably still wont work, you will have to delete the images from the product_images table and upload all the images for the products again. All the Images are found in the images folder in public folder

**Comment by davidtrushkov** [comment]
https://laravel.com/docs/5.2/elixir

[https://www.laravel.com/assets/img/laravel-logo.png]<https://laravel.com/docs/5.2/elixir>

Laravel Elixir - Laravel - The PHP Framework For Web Artisans<https://laravel.com/docs/5.2/elixir>
laravel.com
Laravel Elixir. Introduction; Installation & Setup; Running Elixir; Working With Stylesheets. Less; Sass; Plain CSS; Source Maps; Working With Scripts. CoffeeScript




The only reason why I think you cant compile sass is you have to install "gulp" and "npm". Found at the link I gave you.  If that doesn't work, just create a css file and copy all the code from sass file to your new file, and comment out the sass file in your header.

The file image path has to look something like this when you inspect the source code in you web browser.
/store/src/public/ProductPhotos/photos/th-50d59eef10574aeb78a8681541ef7e6bf2a3edd5.jpg

Although it probably still wont work, you will have to delete the images from the product_images table and upload all the images for the products again. All the Images are found in the images folder in public folder
________________________________

**Comment by sethinh** [comment]
Thank you so much.
It work.
