### ISSUE TITLE
Fatal error: require_once()

### ISSUE THREAD

**Issue by guazarito** [davidtrushkov/store#10]
Hi everybody,

I'm not sure if I'm doing it right.
I've built some laravel applications and it has never happened before. 

This time I downloaded the .zip package, unpacked it into my d: drive and then I've run via command dos line the following: 
d:\store\src>php artisan serve

I've also run "composer install". "composer update", gave 777 permission to app/storage,  etc..

However, when I try to access it on my browser, I get the error:

"Warning: require_once(D:\store\src/public/index.php): failed to open stream: No such file or directory in D:\store\src\server.php on line 21

Fatal error: require_once(): Failed opening required 'D:\store\src/public/index.php' (include_path='C:\xampp\php\PEAR') in D:\store\src\server.php on line 21"

Does anyone know how to fix it ?
Many thanks, 

Gustavo

**Comment by davidtrushkov** [comment]
I usually dont download the zip package, when installing a Laravel project. I clone it in the command prompt. One thing you said is  `"Warning: require_once(D:\store\src/public/index.php): failed to open stream: No such file or directory in D:\store\src\server.php on line 21`. My index.php file is out side the src directory for this project. It seems like the index.php file is in the wrong place.

This is how my directory looks like. _(I know you are not suppose to structure it this way)_
![store](https://cloud.githubusercontent.com/assets/12102225/19842460/a5102144-9eef-11e6-9466-667cbcd46ebb.JPG)

**Comment by guazarito** [comment]
Thanks for your reply, davidtrushkov.

I was trying to run it in Windows system, and I could solve it by running it in Ubuntu. 
Maybe the problem can be in Windows.

Anyway, many thanks for your help

Gustavo
