### ISSUE TITLE
beginner help plz!!

### ISSUE THREAD

**Issue by saimonazad** [davidtrushkov/store#3]
I m new to web development .What ide is used to make this store?
I want to edit it to learn.
Thank you. :)

**Comment by davidtrushkov** [comment]
I used JetBrains PhpStorm 2016, but you can use what ever you want. I got it for Free because I'am a Student.

**Comment by saimonazad** [comment]
Thank u very much sir.I didnt expect that u would answer.
Again thank u. :)
