### ISSUE TITLE
using less/saas

### ISSUE THREAD

**Issue by saimonazad** [davidtrushkov/store#4]
Sir , I know its a lot to ask .But can you make a copy of this project without less / saas , just only css?
I am very beginner and noob :) .

Thank you and god bless you.

**Comment by saimonazad** [comment]
I am waiting for your reply. :)

**Comment by davidtrushkov** [comment]
There you go, check the commits in GitHub for the project. I did 3 different commits. Make sure to "gulp", so the main.css file transfers to public folder.

**Comment by davidtrushkov** [comment]
Also delete the paths in the header for app.css and app.scss

**Comment by saimonazad** [comment]
Thank u very much sir ... (y)
