### ISSUE TITLE
gulp issue

### ISSUE THREAD

**Issue by TsenkoTsenov** [davidtrushkov/store#6]
Hey, when i gulp ( successfuly ) and run the project i get this:
![2](https://cloud.githubusercontent.com/assets/12273257/16379817/5b6192a6-3c7c-11e6-980b-d37e2d8d0fe1.png)
Any idea why this is happening ?

**Comment by davidtrushkov** [comment]
Hey, sorry for not getting back to you sooner, was busy this week. This can be the result of multiple things. First thing is check if the CSS and JavaScript files successfully made it into the _'public'_ folder.
It could be you file structure is not set up correctly.
Try to maybe go into one of the main files where all the css hrefs are called and change the path 

If you want show me an image of your Laravel file structure WITH the public folder expanded to show the CSS and JavaScript files (If there are any)

**Comment by linas01** [comment]
Hey, could you please tell me how you solve this issue.
Thank you.
