### ISSUE TITLE
Installation? 

### ISSUE THREAD

**Issue by Arnau3ip** [davidtrushkov/store#7]
Hello, 

I've downloaded your package through git, and after following your instructions , all i see when i start the app is the folder structure inside /public. I use  a vhost pointing there, and i had no problems with other laravel projects. Am i missing something? 

Thanks.

**Comment by davidtrushkov** [comment]
Dont really know what to tell you here. All I know is when I did that project, I moved all the contents of the public folder outside of app/. Probably wasn't the best idea.

**Comment by Arnau3ip** [comment]
It has to point to the root of the project, i forgot to say.

Thanks.
